{
 "title": "Cloud SLA Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" },
   {
    "name": "region",
    "label": "Region",
    "query": "label_values({job=\"app\"},country)"
   },
   {
    "name": "category",
    "label": "Category",
    "query": "label_values({job=\"app\", country=~\"$region\"},category)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values({job=\"app\", country=~\"$region\",  category=~\"$category\"},service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cloud SLA $region",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count({job=\"app\",country=~\"$region\"})/sum({job=\"app\",country=~\"$region\"})"
    }
   ]
  },
  {
   "title": "Number of Servicies $region",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count({job=\"app\",country=~\"$region\"})"
    }
   ]
  },
  {
   "title": "Number of Servicies $region",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count({job=\"app\",country=~\"$region\"})"
    }
   ]
  },
  {
   "title": "Cloud SLA $region",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count({job=\"app\",country=~\"$region\"})/sum({job=\"app\",country=~\"$region\"})"
    }
   ]
  },
  {
   "title": "Hot AWS Regions",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "topk(10,count({job=\"app\",__name__=~\"aws_.*\"}) by (country))",
     "legendFormat": "{{country}} "
    }
   ]
  },
  {
   "title": "AWS Availability $region",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 13, "x": 5, "y": 5 },
   "valueName": "total",
   "targets": [
    {
     "expr": "{__name__=~\"aws_.*\",country=~\"$region\"}"
    }
   ]
  },
  {
   "title": "AWS Global Services",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "sum({__name__=\"aws_health\",service!=\"No recent events.\"}) by (service)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ]
  }
 ]
}