{
 "title": "Corona Stats V2",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Prometheus_Server", "query": "prometheus" },
   {
    "name": "country",
    "label": "Select your country here:",
    "query": "label_values({job=\"app\"},country)"
   },
   {
    "name": "stats",
    "label": "Select what you search:",
    "query": "label_values({job=\"app\"},__name__)"
   }
  ]
 },
 "panels": [
  {
   "title": "COVID-19  Mortality $country",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum({job=\"app\",__name__=\"deathCases\", country=~\"$country\"})/sum({job=\"app\",__name__=\"recoveredCases\", country=~\"$country\"})) * 100"
    }
   ]
  },
  {
   "title": "COVID-19  Serious Cases percentile $country",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum({job=\"app\",__name__=\"seriosCases\", country=~\"$country\"})/sum({job=\"app\",__name__=\"activeCases\", country=~\"$country\"})) * 100"
    }
   ]
  },
  {
   "title": "COVID-19  Recover $country",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum({job=\"app\",__name__=\"recoveredCases\", country=~\"$country\"})/sum({job=\"app\",__name__=\"activeCases\", country=~\"$country\"})) * 100"
    }
   ]
  },
  {
   "title": "Report Tests / Confirmed Cases  $country",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum({job=\"app\",__name__=\"activeCases\", country=~\"$country\"})/sum({job=\"app\",__name__=\"testsPerformed\", country=~\"$country\"})) * 100"
    }
   ]
  },
  {
   "title": "Top 10 $stats",
   "type": "bargauge",
   "gridPos": { "h": 27, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "topk(10,{job=\"app\",__name__=~\"[[stats]]\"})",
     "legendFormat": "{{country}} "
    }
   ]
  },
  {
   "title": "World Wide Stats for $stats",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 27, "w": 15, "x": 4, "y": 5 },
   "valueName": "total",
   "targets": [
    {
     "expr": "$stats{country=~\"$country\"}"
    }
   ]
  },
  {
   "title": "Statistic Active Cases",
   "type": "table",
   "gridPos": { "h": 27, "w": 5, "x": 19, "y": 5 },
   "targets": [
    {
     "expr": "sum({job=\"app\",__name__=~\"$stats\", country=~\"$country\"}) by(country,__name__)",
     "legendFormat": "{{country}] {{__name__}}"
    }
   ]
  },
  {
   "title": "COVID-19 Evolution Graph for $stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\"$stats\",country=~\"[[country]]\"}) by (country,__name__)"
    }
   ]
  }
 ]
}